#############################################################
#           Checkout the private repo
#############################################################
name: 'CheckoutFuseEngine'
description: 'Clear GitHub action cache for a specific branch.'

inputs:
  branch:
    description: 'The branch to checkout'
    required: true
  github-token:
    description: The GitHub token to use.
    required: true

runs:
  using: "composite"
  steps:
   - name: Cloning FuseEngine ...
     uses: actions/checkout@v4
     with:
      repository: spinell/FuseEngine
      ref: ${{ inputs.branch }}
      token: ${{ inputs.github-token }}
      submodules: recursive
      fetch-depth: 0
