# This is a basic workflow to help you get started with Actions

name: Build-Branch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-gcc13:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout FuseEngine
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          ref: dev
          token: ${{ secrets.PAT }}
          submodules: recursive

      # Runs a set of commands using the runners shell
      - name: CMake Configure Debug (gcc 13)
        run: cmake --preset gcc-13-debug -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build Debug (gcc 13)
        run: cmake --build build/gcc-13-debug

      - name: Run test Debug (gcc 13)
        run: ctest --test-dir build/gcc-13-debug --verbose

      - name: Install Debug (gcc 13)
        run: cmake --install build/gcc-13-debug  --prefix ./install/gcc-13-debug

      - uses: actions/upload-artifact@v4
        with:
          name: install-ubuntu-gcc-13-debug
          path: ./install/gcc-13-debug

      - run: echo "This job's status is ${{ job.status }}."

  build-gcc14:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout FuseEngine
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          ref: dev
          token: ${{ secrets.PAT }}
          submodules: recursive

      # Runs a set of commands using the runners shell
      - name: CMake Configure Debug (gcc 14)
        run: cmake --preset gcc-14-debug -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build Debug (gcc 14)
        run: cmake --build build/gcc-14-debug

      - name: Run test Debug (gcc 14)
        run: ctest --test-dir build/gcc-14-debug --verbose

      - name: Install Debug (gcc 14)
        run: cmake --install build/gcc-14-debug  --prefix ./install/gcc-14-debug

      - uses: actions/upload-artifact@v4
        with:
          name: install-ubuntu-gcc-14-debug
          path: ./install/gcc-14-debug

      - name: Install Debug (gcc 14)
        run: |
          cpack --config build/gcc-14-debug/CPackConfig.cmake -G ZIP -B build/gcc-14-debug/package
          cpack --config build/gcc-14-debug/CPackConfig.cmake -G 7Z  -B build/gcc-14-debug/package
          cpack --config build/gcc-14-debug/CPackConfig.cmake -G TAR -B build/gcc-14-debug/package

      - uses: actions/upload-artifact@v4
        with:
          name: FuseEngine-0.0.1-Linux-gcc-14.zip
          path: build/gcc-14-debug/package/FuseEngine-0.0.1-Linux.zip

      - uses: actions/upload-artifact@v4
        with:
          name: FuseEngine-0.0.1-Linux-gcc-14.7z
          path: build/gcc-14-debug/package/FuseEngine-0.0.1-Linux.7z

      - uses: actions/upload-artifact@v4
        with:
          name: FuseEngine-0.0.1-Linux-gcc-14.tar
          path: build/gcc-14-debug/package/FuseEngine-0.0.1-Linux.tar

      - run: echo "This job's status is ${{ job.status }}."
