################################################################################
# TOTO concurrency
################################################################################
name: Build-Branch-Windows2022
description: 'Performs a build branch on windows 2022'


on:
  workflow_dispatch:
    inputs:
      warningsAsErrors:
        description: 'Build with warnings as errors'
        required: true
        type: 'boolean'
        default: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  windows:
    name: Windows-2022-${{ matrix.buildConfig }}
    runs-on: Windows-2022
    strategy:
      fail-fast: false # if one job in the matrix fail, don't cancel other jobs inthe matr
      matrix:
        buildConfig: [Debug, RelWithDebInfo, Release]
    env:
        BUILD_DIR: "build/ninja-multi-config"
        INSTALL_DIR: "install/ninja-multi-config"

    steps:
      # Clone the repo
      - name: Checkout FuseEngine
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          ref: dev
          token: ${{ secrets.PAT }}
          submodules: recursive

      # setup MSVC shell
      - name: Set Visual Studio command line
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - run: ninja.exe --version
      - run: cmake.exe --version
      - run: clang.exe --version

      - name: Running cmake configure (cl)...
        run: |
          cmake --preset ninja-multi-config `
            -B ./build-cl `
            -DCMAKE_C_COMPILER=cl `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DCMAKE_COMPILE_WARNING_AS_ERROR=${{ github.event.inputs.warningsAsErrors }}

      - run: cmake --build    ./build-cl --config       ${{ matrix.buildConfig }}
      - run: ctest --test-dir ./build-cl --build-config ${{ matrix.buildConfig }} --rerun-failed --output-on-failure
      - run: cmake --install  ./build-cl --prefix       ${{ env.INSTALL_DIR}}     --config ${{ matrix.buildConfig }}

      - name: Running cmake configure ...
        run: |
          cmake --preset ninja-multi-config (clang-cl) `
            -B ./build-clang-cl `
            -DCMAKE_C_COMPILER='clang-cl.exe' `
            -DCMAKE_CXX_COMPILER='clang-cl.exe' `
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DCMAKE_COMPILE_WARNING_AS_ERROR=${{ github.event.inputs.warningsAsErrors }}
      - run: cmake --build    ./build-clang-cl --config       ${{ matrix.buildConfig }}
      - run: ctest --test-dir ./build-clang-cl --build-config ${{ matrix.buildConfig }} --rerun-failed --output-on-failure
      - run: cmake --install  ./build-clang-cl --prefix       ${{ env.INSTALL_DIR}}     --config ${{ matrix.buildConfig }}


      - name: Running cmake configure (clang)...
        run: |
          cmake --preset ninja-multi-config `
            -B ./build-clang `
            -DCMAKE_C_COMPILER='clang.exe' `
            -DCMAKE_CXX_COMPILER='clang.exe' `
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DCMAKE_COMPILE_WARNING_AS_ERROR=${{ github.event.inputs.warningsAsErrors }}
      - run: cmake --build    ./build-clang --config       ${{ matrix.buildConfig }}
      - run: ctest --test-dir ./build-clang --build-config ${{ matrix.buildConfig }} --rerun-failed --output-on-failure
      - run: cmake --install  ./build-clang --prefix       ${{ env.INSTALL_DIR}}     --config ${{ matrix.buildConfig }}
