# This is a basic workflow to help you get started with Actions

name: Build-Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Public
        uses: actions/checkout@v4
        with:
          repository: spinell/3DGame
          path: 3DGame
          token: ${{ secrets.PUBLIC_PAT }}
          submodules: recursive

      - name: Checkout Private
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          token: ${{ secrets.pat }}
          submodules: recursive
      
      - name: Run a one-line script
        run: ls -la .

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
