# This is a basic workflow to help you get started with Actions

name: Build-Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout FuseEngine
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          ref: dev
          token: ${{ secrets.PAT }}
          submodules: recursive

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -la .
          env
          ninja --version
          cmake --version

      # Runs a set of commands using the runners shell
      - name: CMake Configure Debug (gcc 14)
        run: cmake --preset gcc-14-debug -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build Debug (gcc 14)
        run: cmake --build build/gcc-14-debug

      - name: Run test Debug (gcc 14)
        run: ctest ---test-dir build/gcc-14-debug

      - name: Install Debug (gcc 14)
        run: cmake --install build/gcc-14-debug  --prefix ./install/gcc-14-debug
