# This is a basic workflow to help you get started with Actions

name: Build-Branch


# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-gcc13:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    env:
        BUILD_DIR: "build/gcc-13-debug"
        INSTALL_DIR: "install/gcc-13-debug"

    steps:
      - name: Checkout FuseEngine
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          ref: dev
          token: ${{ secrets.PAT }}
          submodules: recursive

      # Runs a set of commands using the runners shell
      - name: CMake Configure Debug (gcc 13)
        run: cmake --preset gcc-13-debug -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build Debug (gcc 13)
        run: cmake --build ${{env.BUILD_DIR}}

      - name: Run test Debug (gcc 13)
        run: ctest --test-dir ${{env.BUILD_DIR}} --verbose

      - name: Install Debug (gcc 13)
        run: cmake --install ${{env.BUILD_DIR}}  --prefix ${{env.INSTALL_DIR}}

      - uses: actions/upload-artifact@v4
        with:
          name: install-ubuntu-gcc-13-debug
          path: ${{env.INSTALL_DIR}}

  build-gcc14:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    env:
        BUILD_DIR: "build/gcc-14-debug"
        INSTALL_DIR: "install/gcc-14-debug"

    steps:
      - name: Checkout FuseEngine
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          ref: dev
          token: ${{ secrets.PAT }}
          submodules: recursive

      # Runs a set of commands using the runners shell
      - name: CMake Configure Debug (gcc 14)
        run: cmake --preset gcc-14-debug -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build Debug (gcc 14)
        run: cmake --build ${{env.BUILD_DIR}}

      - name: Run test Debug (gcc 14)
        run: ctest --test-dir ${{env.BUILD_DIR}} --verbose

      - name: Install Debug (gcc 14)
        run: cmake --install ${{env.BUILD_DIR}}  --prefix ${{env.INSTALL_DIR}}

      - uses: actions/upload-artifact@v4
        with:
          name: install-ubuntu-gcc-14-debug
          path: ${{env.INSTALL_DIR}}

  linux:
    name: ${{ matrix.os }}-${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}-${{ matrix.buildConfig }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # if one job in the matrix fail, don't cancel other jobs inthe matrix
      matrix:
        os: [ ubuntu-24.04]
        buildConfig: [Debug, Release, RelWithDebInfo]
        compiler:
          #- { cc: gcc, cxx: g++, version: 12} GCC 12 does not support std::format
          - { cc: gcc, cxx: g++, version: 13}
          - { cc: gcc, cxx: g++, version: 14}
          - { cc: clang, cxx: clang++, version: 16 }
          - { cc: clang, cxx: clang++, version: 17 }
          - { cc: clang, cxx: clang++, version: 18 }
    env:
        BUILD_DIR: "build/${{matrix.compiler.cc}}-${{matrix.compiler.version}}${{matrix.compiler.buildConfig}}"
        INSTALL_DIR: "install/${{matrix.compiler.cc}}-${{matrix.compiler.version}}${{matrix.compiler.buildConfig}}"
    steps:
      - name: Checkout FuseEngine
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          ref: dev
          token: ${{ secrets.PAT }}
          submodules: recursive
      # Runs a set of commands using the runners shell
      - name: CMake Configure
        env:
          CC: "${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}"
          CXX: "${{ matrix.compiler.cxx }}-${{ matrix.compiler.version }}"
        run: |
          cmake --preset gcc-14-debug \
             -B ${{env.BUILD_DIR}} \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=${{matrix.buildConfig}} \
            -DCMAKE_C_COMPILER=${{env.CC}} \
            -DCMAKE_CXX_COMPILER=${{env.CXX}}

      - name: Build Debug
        run: cmake --build ${{env.BUILD_DIR}}

      - name: Run test
        run: ctest --test-dir ${{env.BUILD_DIR}} --verbose

      - name: Install Debug
        run: cmake --install ${{env.BUILD_DIR}}  --prefix ${{env.INSTALL_DIR}}

      - uses: actions/upload-artifact@v4
        with:
          name: install-ubuntu-${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}-${{matrix.buildConfig}}
          path: ${{env.INSTALL_DIR}}

  windows:
    name: Windows-2022-${{ matrix.buildConfig }}
    runs-on: Windows-2022
    strategy:
      matrix:
        buildConfig: [Debug, RelWithDebInfo, Release]
    env:
        BUILD_DIR: "build/ninja-multi-config"
        INSTALL_DIR: "install/ninja-multi-config"

    steps:
      # Clone the repo
      - name: Checkout FuseEngine
        uses: actions/checkout@v4
        with:
          repository: spinell/FuseEngine
          ref: dev
          token: ${{ secrets.PAT }}
          submodules: recursive

      # Install ninja
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run : ninja --version

      # setup MSVC shell
      - name: Set Visual Studio Architecture
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      # Runs a set of commands using the runners shell
      - name: Running cmake configure ...
        run: cmake --preset ninja-multi-config -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_COMPILE_WARNING_AS_ERROR=OFF

      - name: Running cmake build ...
        run: cmake --build ${{env.BUILD_DIR}} --config ${{ matrix.buildConfig }}

      - name: Running tests ...
        run: ctest --test-dir ${{env.BUILD_DIR}} --build-config ${{ matrix.buildConfig }}

      - name: Running cmake install ...
        run: cmake --install ${{env.BUILD_DIR}}  --prefix ${{env.INSTALL_DIR}} --config ${{ matrix.buildConfig }}

      - uses: actions/upload-artifact@v4
        with:
          name: install-windows-${{ matrix.buildConfig }}
          path: ${{env.INSTALL_DIR}}
