name: Test-CheckoutRepoAction
description: 'Test custom acton'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to checkout'
        type: string
        default: 'dev'
        required: true

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - run: mkdir $HOME/ThisRepo
      # Clone the repo (Required to use custom action in this repo)
      - name: Cloning this repo
        uses: actions/checkout@v4
        with:
          path: $HOME/ThisRepo
          submodules: false
          fetch-depth: 0

      - run: ls -ls $HOME/ThisRepo

      - name: Cloning FuseEngine
        uses: ./.github/actions/clone-repo
        with:
          branch: ${{ inputs.branch }}
          github-token: ${{ secrets.PAT }}

      - run: ls -ls $PWD
