name: Test
run-name: Test-RunName
description: Test description
env:
  MY_GLOBAL_ENV: YO


on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: ${{ inputs.print_tags }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }}

  print:
    runs-on: ubuntu-24.04
    if: ${{ inputs.print_tags }}
    steps:
      - name: Display stuffs
        run: |
          echo =============     ENV    =================
          env
          echo ================================================

          echo HOME: $HOME
          which ninja
          which cmake
          which gcc
          which clang


      - name: Display inputs
        run: |
          echo The tags are ${{ inputs.tags }}
          echo The tags are ${{ github.event.inputs.tags }}
          echo Log level ${{ inputs.logLevel }}
          echo Log level ${{ github.event.inputs.logLevel }}
          echo print_tags ${{ inputs.print_tags }}
          echo print_tags ${{ github.event.inputs.print_tags }}

      - name: Print annotation
        run: |
          # See https://docs.github.com/en/actions/how-tos/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging
          echo "::debug::This is a debug message!"

          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"

          echo "::group::My title"
          echo "Inside group"
          echo "::warning Inside group"
          echo "Inside group"
          echo "::endgroup::"


          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
